services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  banking-validation:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: guilhermecjusto/banking-service:v1
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=joao
      - QUARKUS_DATASOURCE_PASSWORD=joao
      - QUARKUS_DATASOURCE_HOST=postgres-db-alura
      - QUARKUS_DATASOURCE_PORT=15433
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
      - URL_BANKING_STATUS=http://banking-status:8080
      - QUARKUS_KAFKA_HOST=kafka
      - QUARKUS_KAFKA_PORT=9092
    depends_on:
      - postgres-db-alura
      - banking-status

  banking-status:
    build:
      context: ../banking-status
      dockerfile: src/main/docker/Dockerfile.jvm
    image: banking-status
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=joao
      - QUARKUS_DATASOURCE_PASSWORD=joao
      - QUARKUS_DATASOURCE_HOST=postgres-db-alura
      - QUARKUS_DATASOURCE_PORT=15433
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
      - QUARKUS_KAFKA_SERVER=kafka
      - QUARKUS_KAFKA_PORT=9092
    depends_on:
      - postgres-db-alura

  postgres-db-alura:
    image: postgres:14
    environment:
      - POSTGRES_USER=joao
      - POSTGRES_PASSWORD=joao
      - POSTGRES_DB=agencia
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

volumes:
  postgres_data:
    driver: local