services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  banking-validation:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: guilhermecjusto/banking-service:v1
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=joao
      - QUARKUS_DATASOURCE_PASSWORD=joao
      - QUARKUS_DATASOURCE_HOST=postgres-db-alura
      - QUARKUS_DATASOURCE_PORT=5432
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
    depends_on:
      - postgres-db-alura

  postgres-db-alura:
    image: postgres:14
    environment:
      - POSTGRES_USER=joao
      - POSTGRES_PASSWORD=joao
      - POSTGRES_DB=agencia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local