%dev.quarkus.http.port=8082

quarkus.micrometer.export.prometheus.path=/metrics
quarkus.rest-client.banking-status.url=${URL_BANKING_STATUS}

quarkus.datasource.db-kind=postgresql

%prod.quarkus.datasource.reactive.url=postgresql://${QUARKUS_DATASOURCE_HOST}:${QUARKUS_DATASOURCE_PORT}/agencia
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
%prod.quarkus.hibernate-orm.database.generation=none

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.datasource.devservices.db-name=agencia

quarkus.kafka.devservices.enabled=false

kafka.bootstrap.servers=${QUARKUS_KAFKA_SERVER:localhost}:${QUARKUS_KAFKA_PORT:9092}
mp.messaging.outgoing.nova-situacao-channel.connector=smallrye-kafka
mp.messaging.outgoing.nova-situacao-channel.topic=agencia.situacao.alterada
mp.messaging.outgoing.nova-situacao-channel.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer