apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: banking-system
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS agencia (
      id SERIAL PRIMARY KEY,
      nome TEXT NOT NULL,
      razao_social TEXT NOT NULL,
      cnpj VARCHAR(18) NOT NULL,
      situacao_cadastral VARCHAR(7) NOT NULL,
      data_atualizacao TIMESTAMP
    );
        
    CREATE TABLE IF NOT EXISTS endereco (
      id SERIAL PRIMARY KEY,
      rua TEXT NOT NULL,
      logradouro TEXT NOT NULL,
      complemento TEXT NOT NULL,
      numero INT NOT NULL      
    )    
        
    INSERT INTO agencia (nome, razao_social, cnpj, situacao_cadastral, data_atualizacao)
    VALUES ('Agência BSB', 'Agência de Brasília LTDA', '01.001.001/0001-01', 'ATIVO', '2023-01-01');
        
    INSERT INTO endereco (rua, logradouro, complemento, numero)
    VALUES ('Rua das Flores', 'Avenida Principal', 'Apto 101', 123);